"""GHand SDK version information."""

SDK_VERSION_MAJOR = 2
SDK_VERSION_MINOR = 0
SDK_VERSION_REVISION = 0

__version__ = "{}.{}.{}".format(SDK_VERSION_MAJOR, SDK_VERSION_MINOR, SDK_VERSION_REVISION)
